Repository opensearch-project/dashboards-notifications, pull requests merged in 2023-11, with the labels that each got.

#135 Onboard jenkins prod docker images to github actions
  .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Labels: enhancement, backport 2.x

#139 Replaced wrongly formatted mock Slack URLs with properly formatted mock Slack URLs
  .cypress/fixtures/test_slack_channel.json
  .cypress/integration/channels.spec.js
  public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap
  test/mocks/mockData.ts
Labels: backport 2.x, OSCI

#144 Replace all wrong Chime urls with correct ones
  .cypress/fixtures/test_chime_channel.json
  .cypress/integration/channels.spec.js
  public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap
  public/pages/CreateChannel/__tests__/ChimeSettings.test.tsx
  test/mocks/mockData.ts
Labels: backport 2.x

#145 Fix: CI flow on windows main
  .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Labels: backport 2.x
