Repository opensearch-project/dashboards-notifications, pull requests merged in 2023-07, with the labels that each got.

#46 Move notification plugin into management section on left navigation menu
  .eslintrc.js
  opensearch_dashboards.json
  package.json
  public/plugin.ts
  public/types.ts
Labels: enhancement, backport 2.x, v2.9.0

#71 Drafted 2.9 release notes.
  release-notes/opensearch-dashboards-notifications.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#79 fix: CVE of tough-cookie and word-wrap
  package.json
  yarn.lock
Labels: security vulnerability, v2.9.0, backport 2.9

#89 stabilize cypress test case
  .cypress/integration/channels.spec.js
  .cypress/support/commands.js
Labels: backport 2.x

#84 upgrade backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x
