Repository opensearch-project/dashboards-notifications, pull requests merged in 2024-09, with the labels that each got.

#244 Persist dataSourceId across applications under new Nav change
  public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
  public/components/PageHeader/PageHeader.tsx
  public/pages/Emails/EmailSenders.tsx
  public/pages/Main/Main.tsx
  public/plugin.ts
  public/utils/constants.ts
Labels: backport 2.x

#248 Releas notes
  public/pages/Main/Main.tsx
  release-notes/opensearch-dashboards-notifications.release-notes-2.17.0.0.md
Labels: backport 2.x

#251 Update notes
  public/pages/Main/Main.tsx
  release-notes/opensearch-dashboards-notifications.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#249 [Backport 2.x] Persist dataSourceId across applications under new Nav change (#244)
  public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
  public/components/PageHeader/PageHeader.tsx
  public/pages/Emails/EmailSenders.tsx
  public/pages/Main/Main.tsx
  public/plugin.ts
  public/utils/constants.ts
Labels: backport 2.17

#256 [Fit & Finish] Updated Fit and Finish guidelines
  public/components/ContentPanel/ContentPanel.tsx
  public/components/__tests__/__snapshots__/ContentPanel.test.tsx.snap
  public/pages/Channels/Channels.tsx
  public/pages/Channels/__tests__/__snapshots__/ChannelDetails.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/Channels.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/DetailsListModal.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/DetailsTableModal.test.tsx.snap
  public/pages/Channels/components/ChannelActions.tsx
  public/pages/Channels/components/details/ChannelDetails.tsx
  public/pages/Channels/components/details/ChannelDetailsActions.tsx
  public/pages/Channels/components/modals/DeleteChannelModal.tsx
  public/pages/Channels/components/modals/DetailsListModal.tsx
  public/pages/Channels/components/modals/DetailsTableModal.tsx
  public/pages/Channels/components/modals/MuteChannelModal.tsx
  public/pages/CreateChannel/CreateChannel.tsx
  public/pages/CreateChannel/__tests__/__snapshots__/ChannelNamePanel.test.tsx.snap
  public/pages/CreateChannel/__tests__/__snapshots__/CreateChannel.test.tsx.snap
  public/pages/CreateChannel/components/modals/CreateRecipientGroupModal.tsx
  public/pages/CreateChannel/components/modals/CreateSESSenderModal.tsx
  public/pages/CreateChannel/components/modals/CreateSenderModal.tsx
  public/pages/Emails/CreateRecipientGroup.tsx
  public/pages/Emails/CreateSESSender.tsx
  public/pages/Emails/CreateSender.tsx
  public/pages/Emails/EmailGroups.tsx
  public/pages/Emails/EmailSenders.tsx
  public/pages/Emails/__tests__/__snapshots__/CreateRecipientGroup.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/CreateSESSender.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/CreateSender.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/EmailGroups.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/EmailSenders.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/RecipientGroupsTable.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/SendersTable.test.tsx.snap
  public/pages/Emails/components/modals/DeleteRecipientGroupModal.tsx
  public/pages/Emails/components/modals/DeleteSenderModal.tsx
  public/pages/Emails/components/tables/RecipientGroupsTable.tsx
  public/pages/Emails/components/tables/SESSendersTable.tsx
  public/pages/Emails/components/tables/SendersTable.tsx
  public/pages/Main/__tests__/__snapshots__/Main.test.tsx.snap
Labels: backport 2.x, v2.17.0, backport 2.17

#257 edit page changes as per new page header
  public/pages/CreateChannel/CreateChannel.tsx
  public/pages/Emails/CreateRecipientGroup.tsx
  public/utils/constants.ts
Labels: backport 2.x, backport 2.17

#264 Updated workflows to use latest action of upload-artifacts
  .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Labels: backport 2.x, backport 2.17

#271 Fix CI workflow for windows
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Labels: backport 2.x, backport 2.17

#270 Fit and Finish UX Fixes Pt 2.
  public/pages/Channels/__tests__/__snapshots__/ChannelControls.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/Channels.test.tsx.snap
  public/pages/Channels/components/ChannelControls.tsx
  public/pages/Emails/__tests__/__snapshots__/SendersTable.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/SendersTableControls.test.tsx.snap
  public/pages/Emails/components/tables/SendersTableControls.tsx
  public/pages/Main/__tests__/__snapshots__/Main.test.tsx.snap
Labels: backport 2.x, backport 2.17

#283 Revert fit and finish changes from 2.17
  public/components/ContentPanel/ContentPanel.tsx
  public/components/__tests__/__snapshots__/ContentPanel.test.tsx.snap
  public/pages/Channels/Channels.tsx
  public/pages/Channels/__tests__/__snapshots__/ChannelControls.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/ChannelDetails.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/Channels.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/DetailsListModal.test.tsx.snap
  public/pages/Channels/__tests__/__snapshots__/DetailsTableModal.test.tsx.snap
  public/pages/Channels/components/ChannelActions.tsx
  public/pages/Channels/components/ChannelControls.tsx
  public/pages/Channels/components/details/ChannelDetails.tsx
  public/pages/Channels/components/details/ChannelDetailsActions.tsx
  public/pages/Channels/components/modals/DeleteChannelModal.tsx
  public/pages/Channels/components/modals/DetailsListModal.tsx
  public/pages/Channels/components/modals/DetailsTableModal.tsx
  public/pages/Channels/components/modals/MuteChannelModal.tsx
  public/pages/CreateChannel/CreateChannel.tsx
  public/pages/CreateChannel/__tests__/__snapshots__/ChannelNamePanel.test.tsx.snap
  public/pages/CreateChannel/__tests__/__snapshots__/CreateChannel.test.tsx.snap
  public/pages/CreateChannel/components/modals/CreateRecipientGroupModal.tsx
  public/pages/CreateChannel/components/modals/CreateSESSenderModal.tsx
  public/pages/CreateChannel/components/modals/CreateSenderModal.tsx
  public/pages/Emails/CreateRecipientGroup.tsx
  public/pages/Emails/CreateSESSender.tsx
  public/pages/Emails/CreateSender.tsx
  public/pages/Emails/EmailGroups.tsx
  public/pages/Emails/EmailSenders.tsx
  public/pages/Emails/__tests__/__snapshots__/CreateRecipientGroup.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/CreateSESSender.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/CreateSender.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/EmailGroups.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/EmailSenders.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/RecipientGroupsTable.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/SendersTable.test.tsx.snap
  public/pages/Emails/__tests__/__snapshots__/SendersTableControls.test.tsx.snap
  public/pages/Emails/components/forms/CreateRecipientGroupForm.tsx
  public/pages/Emails/components/forms/CreateSESSenderForm.tsx
  public/pages/Emails/components/forms/CreateSenderForm.tsx
  public/pages/Emails/components/modals/DeleteRecipientGroupModal.tsx
  public/pages/Emails/components/modals/DeleteSenderModal.tsx
  public/pages/Emails/components/tables/RecipientGroupsTable.tsx
  public/pages/Emails/components/tables/SESSendersTable.tsx
  public/pages/Emails/components/tables/SendersTable.tsx
  public/pages/Emails/components/tables/SendersTableControls.tsx
  public/pages/Main/__tests__/__snapshots__/Main.test.tsx.snap
Labels: v2.17.1
