Repository opensearch-project/dashboards-notifications, pull requests merged in 2024-10, with the labels that each got.

#287 Fix typo in recipient
  .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
  .github/workflows/dashboards-notifications-test-and-build-workflow.yml
  public/pages/Emails/components/tables/RecipientGroupsTable.tsx
  public/plugin.ts
Labels: backport 2.x, v2.18.0

#290 bug fix to switch to default datasource instead of local cluster when initial loading
  public/pages/Main/Main.tsx
  public/plugin.ts
  public/utils/constants.ts
  server/routes/configRoutes.ts
Labels: backport 2.x, v2.18.0

#293 Added 2.18.0 release notes.
  release-notes/opensearch-dashboards-notifications.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0, backport 2.18

#297 [Multi datasource] Update order of validation; catch exceptions in semver check
  public/pages/Main/Main.tsx
Labels: backport 2.x, backport 2.17, backport 2.18
